import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import DetectionAPI from '../components/DetectionAPI.js'

const elements = ['Get Involved', 'Learn More']


export default function Home() {
 
  return (
    <div className={styles.container}>
      <Head>
      <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />        
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <DetectionAPI />
  
      </main>
      

    
    </div>
  )
}

export { elements }